// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYeppN1fpQJHrss8ulluOn7BOh8VLHQ6w',
    appId: '1:979131778686:web:be11af55a9bcff4c0dfa2f',
    messagingSenderId: '979131778686',
    projectId: 'albify-55066',
    authDomain: 'albify-55066.firebaseapp.com',
    storageBucket: 'albify-55066.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Cx8yuL05pnjYfjzROr0FMecmMn_efpU',
    appId: '1:979131778686:android:f2d87c622a0bdb330dfa2f',
    messagingSenderId: '979131778686',
    projectId: 'albify-55066',
    storageBucket: 'albify-55066.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSqDA2eLK3tVldNY65COjyHXn_rUQRe3I',
    appId: '1:979131778686:ios:57a311336cbd51010dfa2f',
    messagingSenderId: '979131778686',
    projectId: 'albify-55066',
    storageBucket: 'albify-55066.appspot.com',
    iosClientId: '979131778686-cjmluckg4ssvkp55op6fsc8ecil6cstd.apps.googleusercontent.com',
    iosBundleId: 'com.example.albify',
  );
}
